name: OpenAI Knowledge Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'yeahdesk-docs_support.md'
      - 'yeahdesk-docs_product.md'
      - 'yeahdesk-docs_marketing.md'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install axios form-data

      - name: Sync to OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
          OPENAI_VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
        run: |
          node .github/workflows/scripts/sync-openai.js
